[
    [
        "Knowing that a function named fun() resides in a module named mod, choose the proper way to import it:",
        "import fun from mod",
        "import fun",
        "from mod import fun",
        "from fun import mod",
        "c"
    ],
    [
        "Knowing that a function named fun() resides in a module named mod, and it has been imported using the following line: \nimport mod \nchoose the way it can be invoked in your code:",
        "mod.fun()",
        "mod::fun()",
        "fun()",
        "mod‑>fun()",
        "a"
    ],
    [
        "A function returning a list of all entities available in a module is called:",
        "content()",
        "dir()",
        "entities()",
        "listmodule()",
        "b"
    ],
    [
        "The pyc file contains:",
        "compiled Python code",
        "a Python interpreter",
        "a Python compiler",
        "Python source code",
        "a"
    ],
    [
        "When a module is imported, its contents:",
        "are executed once (implicitly)",
        "are executed as many times as they are imported",
        "are ignored",
        "may be executed (explicitly)",
        "a"
    ],
    [
        "A predefined Python variable, storing the current module name, is called:",
        "__modname__",
        "__name__",
        "__mod__",
        "__module__",
        "b"
    ],
    [
        "The following statement:\nfrom a.b import c\ncauses the import of:",
        "entity c from module b from package a",
        "entity a from module b from package c",
        "entity c from module a from package b",
        "entity b from module a from package c",
        "a"
    ],
    [
        "Entering the try: block implies that:",
        "the block will be omitted",
        "all of the instructions from this block will be executed",
        "some of the instructions from this block may not be executed",
        "none of the instructions from this block will be executed",
        "c"
    ],
    [
        "The unnamed except: block:",
        "must be the last one",
        "cannot be used if any named block has been used",
        "can be placed anywhere",
        "must be the first one",
        "a"
    ],
    [
        "The top‑most Python exception is named:",
        "BaseException",
        "Exception",
        "TopException",
        "PythonException",
        "a"
    ],
    [
        "The following statement:\nassert var == 0",
        "will stop the program when var != 0",
        "is erroneous",
        "has no effect",
        "will stop the program when var == 0",
        "d"
    ],
    [
        "ASCII is:",
        "a predefined Python variable name",
        "a standard Python module name",
        "a character name",
        "short for American Standard Code for Information Interchange",
        "d"
    ],
    [
        "UTF‑8 is:",
        "a synonym for “byte”",
        "a form of encoding Unicode code points",
        "the 9th version of the UTF standard",
        "a Python version name",
        "b"
    ],
    [
        "UNICODE is a standard:",
        "honored by the whole universe",
        "for coding floating-point numbers",
        "used by coders from universities",
        "like ASCII, but much more expansive",
        "d"
    ],
    [
        "The following code\nx = ‘\\”\nprint(len(x))\nprints:",
        "1",
        "0",
        "3",
        "2",
        "a"
    ],
    [
        "The following code:\nprint(ord(‘c’) – ord(‘a’))\nprints:",
        "3",
        "2",
        "0",
        "1",
        "b"
    ],
    [
        "The following code\nprint(chr(ord(‘z’) – 2))\nprints:",
        "x",
        "a",
        "z",
        "y",
        "a"
    ],
    [
        "The following code\nprint(3 * ‘abc’ + ‘xyz’)\nprints:",
        "abcabcabcxyz",
        "abcabcxyzxyz",
        "xyzxyzxyzxyz",
        "abcxyzxyzxyz",
        "a"
    ],
    [
        "The following code\nprint(‘Mike’ > “Mikey”)\nprints:",
        "0",
        "False",
        "1",
        "True",
        "b"
    ],
    [
        "The following code:\nprint(float(“1,3”))",
        "prints 1,3",
        "prints 1.3",
        "raises a ValueError exception",
        "prints 13",
        "c"
    ]
]